src/main/default/objects/Commande__c/Commande__c.object-meta.xml
<CustomObject>
    <label>Commande</label>
    <nameField>
        <label>Commande Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commandes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Commande__c/fields/ShippingAddress__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddress__c</fullName>
    <label>ShippingAddress</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Commande__c/fields/ShippingCost__c.field-meta.xml
<CustomField>
    <fullName>ShippingCost__c</fullName>
    <label>ShippingCost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Commande__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Commande__c/fields/Transporter__c.field-meta.xml
<CustomField>
    <fullName>Transporter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transporter</label>
    <referenceTo>Transporter__c</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Transporter__c/Transporter__c.object-meta.xml
<CustomObject>
    <label>Transporter</label>
    <nameField>
        <label>Transporter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transporters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/OrderService.cls
public class OrderService {
    public static void validateOrder(Commande__c cmd, Account acc) {
        if (cmd != null && acc != null && acc.Type == 'Client') {
            cmd.Statut__c = 'Validée';
            // PAS de update ici
        }
    }

    public static void updateShippingInfo(Commande__c cmd, Transporter__c transp) {
        if (cmd != null && transp != null) {
            cmd.ShippingAddress__c = transp.Address__c;
            cmd.ShippingCost__c = transp.Cost__c;
            // PAS de update ici non plus
        }
    }
}